[custom]

;策略组定义
proxy-groups:
  - name: "💻 Github"
    type: select
    proxies:
      - DIRECT
      - REJECT
      - ♻️ 手动更换
      - ALL
    icon: "https://raw.githubusercontent.com/Furina1013/Rules/master/IMG/Github.jpg"

  - name: "🍎 Apple"
    type: select
    proxies:
      - DIRECT
      - REJECT
      - ♻️ 手动更换
      - ALL
    icon: "https://raw.githubusercontent.com/Furina1013/Rules/master/IMG/Apple.jpg"

rules:
  - RULE-SET,Github,🖥 Github
  - RULE-SET,Apple,🍎 Apple

rule-providers:
   Github:   
          type: http
          behavior: classical
          url: "https://raw.githubusercontent.com/Furina1013/Rules/refs/heads/main/Github.list"
          path: ./ruleset/Github.list
          interval: 1800

   Apple:   
          type: http
          behavior: classical
          url: "https://raw.githubusercontent.com/Furina1013/Rules/refs/heads/main/Apple.list"
          path: ./ruleset/Apple.list
          interval: 1800


;启用自定义规则集
clash_rule_base=https://raw.githubusercontent.com/Furina1013/Rules/refs/heads/main/DNS.yml
enable_rule_generator=true
overwrite_original_rules=true
