[custom]

;规则集定义
ruleset=🖥 Github,https://raw.githubusercontent.com/Furina1013/Rules/refs/heads/main/Github.list
ruleset=🍎 Apple,https://raw.githubusercontent.com/Furina1013/Rules/refs/heads/main/Apple.list
ruleset=🐟 Unknown,[]FINAL



;策略组定义
proxy-groups:
  - name: "🖥 Github"
    type: select
    proxies:
      - DIRECT
      - REJECT
      - ♻️ 手动更换
    use: [".*"]
    icon: "https://raw.githubusercontent.com/Furina1013/Rules/master/IMG/Github.jpg"

  - name: "🍎 Apple"
    type: select
    proxies:
      - DIRECT
      - REJECT
      - ♻️ 手动更换
    use: [".*"]
    icon: "https://raw.githubusercontent.com/Furina1013/Rules/master/IMG/Apple.jpg"


;启用自定义规则集
clash_rule_base=https://raw.githubusercontent.com/Furina1013/Rules/refs/heads/main/DNS.yml
enable_rule_generator=true
overwrite_original_rules=true
